from diseaseprognosis.pipeline.st01_data_ingestion import DataIngestionTrainingPipeline
from diseaseprognosis.pipeline.st02_data_validation import DataValidationTrainingPipeline
from diseaseprognosis.pipeline.st03_data_transformation import DataTransformationTrainingPipeline
from diseaseprognosis.pipeline.st04_model_trainer import ModelTrainerTrainingPipeline
from diseaseprognosis.pipeline.st05_model_evaluation import ModelEvaluationTrainingPipeline