from diseaseprognosis.components.data_ingestion import DataIngestion
from diseaseprognosis.components.data_validation import DataValiadtion
from diseaseprognosis.components.data_transformation import DataTransformation